Demo1_ASP_MVC/Controllers/ContactController.cs
using System.Text.Json.Serialization;
using Demo1_ASP_MVC.Models.ContactModels;
using Demo1_ASP_MVC.Models.ViewModels.ContactVM;
using Demo1_ASP_MVC.Service;
using Microsoft.AspNetCore.Mvc;


namespace Demo1_ASP_MVC.Controllers
{
    public class ContactController : Controller
    {

        private readonly string BASEAPI = "http://localhost:5201/api/"; //"https://localhost:7201/api/";

        private readonly SessionManager _sessionManager;
       

        public ContactController(SessionManager sessionManager )
        {
            _sessionManager = sessionManager;
        
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(ListContact));
        }

        public IActionResult AddContact()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddContact(AddContactVM form)
        {

            if (!ModelState.IsValid)
                return View(form);
            
            var contact = new 
            {
                FirstName = form.FirstName,
                LastName = form.LastName,
                Email = form.Email,
                Birthdate = form.Birthdate,
                UserId = _sessionManager.Id
            };

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BASEAPI);
            var reponse = await client.PostAsJsonAsync("Contact/Insert", contact);
            if (reponse.IsSuccessStatusCode)
            {
                Contact result = await reponse.Content.ReadFromJsonAsync<Contact>();
            }
            return RedirectToAction(nameof(ListContact));
        }


        public async Task<IActionResult> ListContact()
        {

           List<Contact> contacts = new List<Contact>();

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BASEAPI);
            var reponse = await client.GetAsync("Contact/GetAll");
            if (reponse.IsSuccessStatusCode)
            {
                contacts = await reponse.Content.ReadFromJsonAsync<List<Contact>>();
            }

            ListContactVM listContacts = new ListContactVM(contacts.OrderBy(c => c.Id).ToList());
           
            return View(listContacts);
        }
        

        public async Task<IActionResult> DeleteContact(int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BASEAPI);
            var reponse = await client.DeleteAsync($"Contact/Delete/{id}");
            if (reponse.IsSuccessStatusCode)
            {
                int nbRows = await reponse.Content.ReadFromJsonAsync<int>();
            }
            
            return RedirectToAction(nameof(ListContact));
        }

        public async Task<IActionResult> ModifyContact(int id)
        {
            AddContactVM contact = new AddContactVM();

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BASEAPI);
            var reponse = await client.GetAsync($"Contact/GetById/{id}");
            if (reponse.IsSuccessStatusCode)
            {
                contact = await reponse.Content.ReadFromJsonAsync<AddContactVM>();

            }

            return View(contact);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyContact(AddContactVM form)
        {
            if(!ModelState.IsValid) return View(form);

            
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BASEAPI);
            var reponse = await client.PutAsJsonAsync($"Contact/Update/{form.Id}", form);
            if (reponse.IsSuccessStatusCode)
            {
                int result = await reponse.Content.ReadFromJsonAsync<int>();

            }

            return RedirectToAction(nameof(ListContact));
        }

       
       



    }
}

Demo1_ASP_MVC/Controllers/LoginController.cs
using Demo1_ASP_MVC.Context;
using Demo1_ASP_MVC.Models;
using Demo1_ASP_MVC.Models.ViewModels;
using Demo1_ASP_MVC.Service;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace Demo1_ASP_MVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly SessionManager _sessionManager;

        public LoginController(SessionManager sessionManager)
        {
            _sessionManager = sessionManager;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
           
        }

        [HttpPost]
        public IActionResult Login(AuthLoginFormVM form)
        {
            User? user = FakeDB.Users.SingleOrDefault(u => u.UserName == form.LoginName,null);

            if (user == null)
                ModelState.AddModelError(nameof(form.LoginName), "l'utilisateur n'existe pas");
            else{
                if (user.Password != form.Password)
                {
                    ModelState.AddModelError(nameof(form.Password), "le mot de passe ne correspond pas !!!");
                }
                
                ValidatePassword(form);
                            
            }
            
            if (!ModelState.IsValid)
                return View();

            // ici remplir la session
            _sessionManager.Id = user.Id;
            _sessionManager.Email = user.Email;
            _sessionManager.UserName = user.UserName;
            return RedirectToAction("Index", "Home");
            
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(UserRegisterViewModel registerViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            FakeDB.Users.Add(new User(
                FakeDB.Users.Last().Id + 1,
                registerViewModel.Email,
                registerViewModel.UserName,
                registerViewModel.Password));
            return RedirectToAction("Index", "Home");
        }


        public IActionResult Logout()
        {
            _sessionManager.Clear();
            return RedirectToAction("Index", "Home");
        }




        private void ValidatePassword(AuthLoginFormVM form)
        {
            string password = form.Password;
            string min_pattern = @"[a-z]+";
            string maj_pattern = @"[A-Z]+";
            string numb_pattern = @"[0-9]+";
            string symb_pattern = @"[@\-+=#_]+";
            if (!Regex.IsMatch(password, min_pattern, RegexOptions.None))
                ModelState.AddModelError(nameof(form.Password), "Le mot de passe ne contient pas de minuscule.");
            if (!Regex.IsMatch(password, maj_pattern, RegexOptions.None))
                ModelState.AddModelError(nameof(form.Password), "Le mot de passe ne contient pas de majuscule.");
            if (!Regex.IsMatch(password, numb_pattern, RegexOptions.None))
                ModelState.AddModelError(nameof(form.Password), "Le mot de passe ne contient pas de chiffre.");
            if (!Regex.IsMatch(password, symb_pattern, RegexOptions.None))
                ModelState.AddModelError(nameof(form.Password), "Le mot de passe ne contient pas de symbole.");
        }
    }
}

Demo1_ASP_MVC/Controllers/MathController.cs
using Microsoft.AspNetCore.Mvc;

namespace Demo1_ASP_MVC.Controllers
{
    public class MathController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("Math/TableCroise")]
        public IActionResult TableauCroise()
        {
            return View();
        }

        [Route("Math/Carre/{nombre}")]
        [Route("Math/{nombre}/Carre")]
        public string Carre(int nombre)
        {
            return $"{nombre}² = {nombre * nombre}";
        }

        [Route("Math/Multiple/{nombre}")]
        [Route("Math/Table/{nombre}")]
        public string[] Multiplication(int nombre)
        {
            string [] results = new string [10];
            for (int i = 0; i < results.Length; i++)
            {
                int result = (i+1)*nombre;
                results[i] = $" {i+1} * {nombre} = {result}";
            }
            return results;
        }

        [Route("Math/Divison/{nombre1}/{nombre2}")]
        [Route("Math/Divison")]
        [Route("Math/{nombre1}/diviséPar/{nombre2}")]
        public string Division(int nombre1, int nombre2)
        {
            if (nombre2 == 0)
            {
                return "Vers l'infini";
            }
            else
            {
                return $"{nombre1} / {nombre2} = {(double)nombre1 / nombre2}";
            }
        }
    }
}

Demo1_ASP_MVC/Controllers/ProductController.cs
using Demo1_ASP_MVC.Context;
using Demo1_ASP_MVC.Models;
using Demo1_ASP_MVC.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Demo1_ASP_MVC.Controllers
{
    public class ProductController : Controller
    {
        [ViewData]
        public string Title { get => "Shopping"; }

        

        public IActionResult Index()
        {
            return RedirectToAction(nameof(List));
        }

        public IActionResult List()
        {
            ViewData["Title2"]= ", faites votre choix :";

            ListViewModel listViewModel = new ListViewModel(FakeDB.Products);
           

            return View(listViewModel);
        }

        [HttpPost]
        public IActionResult AddProduct(string product)
        {
            FakeDB.Products.Add(new Product(product));
            return RedirectToAction("List");
        }
    }
}

Demo1_ASP_MVC/Views/Shared/_Layout.cshtml
@using Demo1_ASP_MVC.Service
@inject SessionManager _sessionManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo1_ASP_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Demo1_ASP_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo1_ASP_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark mouse-over" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark mouse-over" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        @if (!_sessionManager.IsValid())
                        {
                             
                            <li class="nav-item">
                                <a class="nav-link text-dark mouse-over" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark mouse-over" asp-area="" asp-controller="Login" asp-action="Register">Register</a>
                            </li>
                            
                        }else{
                            <li class="nav-item">
                                <a class="nav-link text-dark mouse-over" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark mouse-over" asp-area="" asp-controller="Math" asp-action="TableauCroise">Math</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark mouse-over" asp-area="" asp-controller="Contact" asp-action="ListContact">Contacts</a>
                            </li>
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                                 <li class="nav-item mouse-over">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>
                            </div>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Demo1_ASP_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo1_ASP_MVC/Views/Shared/_ProductListPartialView.cshtml
@model Demo1_ASP_MVC.Models.Product

    <li class="m-4">
        <div class =" p-2 border border-dark rounded-2 w-200">
            <h4>Nom : @Model.Nom</h4>
    
            <h4>Prix : @Model.Prix €</h4>
  
            <h4>@(@Model.Stock > 10 ? "En stock" : @Model.Stock > 5 ? "Presque épuisé" : " A commander") </h4>
        </div>
    </li>  

   

<br />
<br />